device: cuda
data:
  batch_size: 128
logger:
  name: new_2.log
model:
  name: new_2.pth
  state_size: 200
  base_name: SAS4Rec
  merge_name: SNPair
  base:
    SAS4Rec:
      num_heads: 8
      num_layers: 2
      dim_feedforward: 200
      dropout: 0.0
      activation: gelu
      shrink: True
  pair:
    pos_weight: 1.0
    l2_emb: 0.0
    loss: cro
train:
  patience: 5
draw:
  name: new_2.png