device: cuda
data:
  batch_size: 128
logger:
  name: new_3.log
model:
  name: new_3.pth
  state_size: 200
  base_name: SASRec
  merge_name: SNPair
  base:
    SAS4Rec:
      num_heads: 8
      num_layers: 2
      dropout: 0.0
  pair:
    pos_weight: 1.0
    l2_emb: 0.0
    loss: cro
train:
  patience: 5
draw:
  name: new_3.png