device: cuda
data:
  batch_size: 128
logger:
  name: SAS4Rec_2.log
model:
  name: SAS4Rec_2.pth
  state_size: 200
  base_name: SAS4Rec
  base:
    SAS4Rec:
      num_heads: 4
      num_layers: 1
      dim_feedforward: 200
      dropout: 0.0
train:
  patience: 5
draw:
  name: SAS4Rec_2.png